import React, { useState, useEffect, useRef } from 'react';
import { BookOpen, Loader2, FileDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import remarkGfm from 'remark-gfm';
import rehypeKatex from 'rehype-katex';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

interface SpecPoint {
  id: string;
  content: string;
  topic?: string;
}

interface DynamicRevisionGuideProps {
  productId: string;
  subjectName?: string;
  tier?: 'free' | 'deluxe';
}

export const DynamicRevisionGuide: React.FC<DynamicRevisionGuideProps> = ({
  productId,
  subjectName = 'this subject',
  tier = 'free',
}) => {
  const { user } = useAuth();
  const [topicInput, setTopicInput] = useState('');
  const [generating, setGenerating] = useState(false);
  const [guideContent, setGuideContent] = useState<string | null>(null);
  const [specPoints, setSpecPoints] = useState<SpecPoint[]>([]);
  const [loadingSpecs, setLoadingSpecs] = useState(true);
  const guideRef = useRef<HTMLDivElement>(null);

  // Load spec points on mount
  useEffect(() => {
    const loadSpecs = async () => {
      try {
        const { data, error } = await supabase
          .from('document_chunks')
          .select('id, content, metadata')
          .eq('product_id', productId)
          .limit(200);

        if (error || !data) { setLoadingSpecs(false); return; }

        const specs = data
          .filter((c: any) => String(c.metadata?.content_type || '') === 'specification')
          .map((c: any) => ({
            id: c.id,
            content: c.content,
            topic: c.metadata?.topic || c.content.slice(0, 80),
          }));

        setSpecPoints(specs);
      } catch (err) {
        console.error('Failed to load spec points:', err);
      } finally {
        setLoadingSpecs(false);
      }
    };
    loadSpecs();
  }, [productId]);

  const handleGenerate = async (topic?: string) => {
    const query = topic || topicInput.trim();
    if (!query) return;
    setTopicInput(query);
    setGenerating(true);
    setGuideContent(null);

    try {
      const { data: sessionData } = await supabase.auth.getSession();
      const headers: Record<string, string> = {
        'Content-Type': 'application/json',
        'apikey': SUPABASE_ANON_KEY,
      };
      if (sessionData.session?.access_token) {
        headers['Authorization'] = `Bearer ${sessionData.session.access_token}`;
      }

      const response = await fetch(`${SUPABASE_URL}/functions/v1/generate-revision-guide`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
          product_id: productId,
          spec_code: query,
          spec_name: query,
          board: 'dynamic',
          options: ['exam_technique', 'application'],
          past_paper_context: '',
          diagram_context: '',
          user_id: user?.id,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        if (response.status === 429) {
          toast.error(errorData.message || 'Rate limit reached. Try again later.');
          return;
        }
        throw new Error(errorData.error || `Request failed with status ${response.status}`);
      }

      const data = await response.json();
      setGuideContent(data.content || 'Unable to generate guide. Please try again.');
    } catch (err) {
      console.error('Error generating guide:', err);
      toast.error('Failed to generate revision guide. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleReset = () => {
    setGuideContent(null);
    setTopicInput('');
  };

  const handleDownload = async () => {
    if (!guideContent) return;
    try {
      const { marked } = await import('marked');
      const html2pdf = (await import('html2pdf.js')).default;

      const htmlContent = marked(guideContent, { async: false }) as string;
      const container = document.createElement('div');
      container.style.cssText = 'position:fixed;left:-9999px;top:0;width:210mm;background:#ffffff;z-index:-1;';
      container.innerHTML = `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; line-height: 1.7; padding: 10px;">
          <div style="font-size: 22px; font-weight: 700; margin-bottom: 16px; border-bottom: 3px solid #7C3AED; padding-bottom: 12px;">${subjectName} — ${topicInput}</div>
          <div style="font-size: 11px; color: #9ca3af; margin-bottom: 20px;">Revision Guide · Generated by A* AI</div>
          ${htmlContent}
          <div style="text-align: center; margin-top: 40px; border-top: 2px solid #E9D5FF; padding-top: 16px; font-size: 11px; color: #9ca3af;">Generated by A* AI · astarai.co.uk</div>
        </div>
      `;
      document.body.appendChild(container);

      // Apply page-break styles via JS to avoid <style> tag parsing issues
      container.querySelectorAll('h1,h2,h3,h4').forEach(el => {
        (el as HTMLElement).style.pageBreakAfter = 'avoid';
        (el as HTMLElement).style.breakAfter = 'avoid';
      });
      container.querySelectorAll('img,figure,svg,table').forEach(el => {
        (el as HTMLElement).style.pageBreakInside = 'avoid';
        (el as HTMLElement).style.breakInside = 'avoid';
      });
      container.querySelectorAll('ul,ol,blockquote').forEach(el => {
        (el as HTMLElement).style.pageBreakInside = 'avoid';
        (el as HTMLElement).style.breakInside = 'avoid';
      });

      await html2pdf()
        .set({
          margin: [15, 20, 15, 20],
          filename: `Revision-Guide-${topicInput.replace(/[^a-zA-Z0-9]/g, '-')}.pdf`,
          image: { type: 'jpeg', quality: 0.95 },
          html2canvas: { scale: 2, useCORS: true, logging: false },
          jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
          pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
        })
        .from(container.firstElementChild)
        .save();

      toast.success('PDF downloaded successfully!');
      document.body.removeChild(container);
    } catch (err) {
      console.error('PDF error:', err);
      toast.error('Failed to generate PDF.');
    }
  };

  // Guide generated view
  if (guideContent) {
    return (
      <div className="space-y-3">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-gradient-brand">
            <BookOpen className="w-5 h-5 text-primary-foreground" />
          </div>
          <div className="flex-1">
            <h3 className="font-semibold text-foreground text-sm">Revision Guide</h3>
            <p className="text-xs text-muted-foreground">{topicInput}</p>
          </div>
          <Button variant="outline" size="sm" onClick={handleDownload} className="gap-1.5 text-xs">
            <FileDown className="w-3.5 h-3.5" /> PDF
          </Button>
        </div>
        <div ref={guideRef} className="max-h-[400px] overflow-y-auto pr-1 prose prose-sm dark:prose-invert max-w-none">
          <ReactMarkdown remarkPlugins={[remarkMath, remarkGfm]} rehypePlugins={[rehypeKatex]}>
            {guideContent}
          </ReactMarkdown>
        </div>
        <Button variant="outline" size="sm" onClick={handleReset} className="w-full">
          Generate Another Guide
        </Button>
      </div>
    );
  }

  // Input view with spec point selector
  return (
    <div className="space-y-3">
      <div className="flex items-center gap-3">
        <div className="p-2 rounded-lg bg-gradient-brand">
          <BookOpen className="w-5 h-5 text-primary-foreground" />
        </div>
        <div>
          <h3 className="font-semibold text-foreground">Revision Guide</h3>
          <p className="text-xs text-muted-foreground">
            Select a spec point or enter a topic
          </p>
        </div>
      </div>

      {/* Free text input */}
      <div className="relative">
        <input
          type="text"
          value={topicInput}
          onChange={(e) => setTopicInput(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
          placeholder={`Enter a topic from ${subjectName}...`}
          className="w-full px-3 py-2.5 text-sm rounded-lg border border-border bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
        />
      </div>

      <Button
        onClick={() => handleGenerate()}
        disabled={!topicInput.trim() || generating}
        className="w-full bg-gradient-brand hover:opacity-90 text-primary-foreground"
        size="sm"
      >
        {generating ? (
          <>
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            Generating...
          </>
        ) : (
          <>
            <BookOpen className="w-4 h-4 mr-2" />
            Generate Revision Guide
          </>
        )}
      </Button>

      {/* Spec points browser */}
      {!generating && specPoints.length > 0 && (
        <div className="space-y-2">
          <p className="text-xs font-medium text-muted-foreground">Or select a spec point:</p>
          <div className="max-h-[200px] overflow-y-auto space-y-1 pr-1">
            {specPoints.map((sp) => (
              <button
                key={sp.id}
                onClick={() => handleGenerate(sp.topic || sp.content.slice(0, 80))}
                className="w-full text-left px-3 py-2 text-xs rounded-md border border-border hover:bg-muted/50 transition-colors line-clamp-2"
              >
                {sp.topic || sp.content.slice(0, 100)}
              </button>
            ))}
          </div>
        </div>
      )}

      {loadingSpecs && (
        <div className="flex items-center justify-center py-2">
          <Loader2 className="w-4 h-4 animate-spin text-muted-foreground" />
          <span className="text-xs text-muted-foreground ml-2">Loading spec points...</span>
        </div>
      )}
    </div>
  );
};
