-- =============================================================================
-- Migration: Add content_source column + seed Edexcel Economics mock papers
-- Date: 2026-04-12
-- =============================================================================

-- 1. Add content_source column to track verbatim vs representative questions
ALTER TABLE public.mock_papers
  ADD COLUMN IF NOT EXISTS content_source TEXT NOT NULL DEFAULT 'representative'
  CHECK (content_source IN ('verbatim', 'representative'));

-- 2. Delete any existing seed data from the original migration (those had wrong total_marks)
DELETE FROM public.mock_papers
WHERE exam_board IN ('Edexcel', 'AQA') AND total_marks = 80;

-- 3. Seed 4 Edexcel Economics papers with proper structure
-- Each paper: Section A (data response), Section B (data response), Section C (essay choice)
-- Marks: 5 + 8 + 10 + 12 + 15 = 50 per data response section, 25 for essay = 100 total

-- Paper 1 June 2023
INSERT INTO public.mock_papers (exam_board, subject, paper_number, paper_name, year, total_marks, time_limit_minutes, content_source, sections, questions)
VALUES (
  'Edexcel', 'Economics', 1,
  'Edexcel Economics A Paper 1: Markets and Business Behaviour (June 2023)',
  2023, 100, 120, 'representative',
  '[{"id":"A","name":"Section A: Data Response — Housing Market","questions":["1a","1b","1c","1d","1e"]},{"id":"B","name":"Section B: Data Response — Energy Market","questions":["2a","2b","2c","2d","2e"]},{"id":"C","name":"Section C: Essay (choose one)","questions":["3","4"]}]'::jsonb,
  '[
    {"question_number":"1a","question_text":"With reference to Extract A, identify two significant features of the data shown.","marks_available":5,"question_type":"5-marker","section":"A","extract_text":"Extract A shows data on UK house prices and housing supply from 2018 to 2023. Average house prices rose from £230,000 in 2018 to £290,000 in 2023, a 26% increase. Over the same period, the number of new housing completions fell from 195,000 to 170,000 per year. The ratio of median house prices to median earnings reached 8.3 in 2023, compared to 7.8 in 2018."},
    {"question_number":"1b","question_text":"With reference to the information provided, explain how the concept of price elasticity of supply is relevant to the UK housing market.","marks_available":8,"question_type":"8-marker","section":"A"},
    {"question_number":"1c","question_text":"With reference to Extract B and your own knowledge, assess the view that government subsidies for first-time buyers are the most effective policy to improve housing affordability.","marks_available":10,"question_type":"10-marker","section":"A","extract_text":"Extract B: The government introduced the Help to Buy scheme in 2013, providing equity loans to first-time buyers. By 2023, the scheme had supported over 350,000 purchases. Critics argue the policy inflated house prices by increasing demand without addressing supply constraints. The Office for Budget Responsibility estimated that Help to Buy increased house prices by 0.8% overall, but by up to 5% in some areas."},
    {"question_number":"1d","question_text":"With reference to the extracts and your own knowledge, evaluate government intervention in the UK housing market. You should consider both demand-side and supply-side policies.","marks_available":12,"question_type":"12-marker","section":"A"},
    {"question_number":"1e","question_text":"Evaluate the view that the UK housing market is a clear example of market failure that justifies significant government intervention.","marks_available":15,"question_type":"15-marker","section":"A"},
    {"question_number":"2a","question_text":"With reference to Extract C, identify two significant features of the data shown.","marks_available":5,"question_type":"5-marker","section":"B","extract_text":"Extract C shows UK electricity generation by source (2018–2023). Renewable energy generation increased from 33% to 42% of total generation. Gas-fired generation fell from 40% to 33%. Nuclear remained roughly constant at 15%. Average wholesale electricity prices tripled from £50/MWh in 2020 to £150/MWh in 2022, before falling to £90/MWh in 2023."},
    {"question_number":"2b","question_text":"With reference to the information provided, explain how negative externalities arise in the energy market and why they may lead to market failure.","marks_available":8,"question_type":"8-marker","section":"B"},
    {"question_number":"2c","question_text":"With reference to Extract D and your own knowledge, assess the effectiveness of carbon taxes as a method of correcting market failure in the energy market.","marks_available":10,"question_type":"10-marker","section":"B","extract_text":"Extract D: The UK Emissions Trading Scheme (UK ETS) replaced the EU ETS in 2021. Carbon prices rose from £50 per tonne in 2021 to £80 per tonne in 2023. Research suggests the scheme has accelerated the shift from coal to gas generation but has had limited impact on the transition to renewable energy. Industry groups argue that high carbon prices damage international competitiveness, while environmental campaigners say the price remains too low to meet net zero targets by 2050."},
    {"question_number":"2d","question_text":"With reference to the extracts and your own knowledge, evaluate the impact of subsidies for renewable energy on economic efficiency and resource allocation.","marks_available":12,"question_type":"12-marker","section":"B"},
    {"question_number":"2e","question_text":"Evaluate the view that government intervention through regulation is more effective than market-based policies in achieving environmental objectives in the energy market.","marks_available":15,"question_type":"15-marker","section":"B"},
    {"question_number":"3","question_text":"Evaluate the view that monopoly power is always detrimental to consumer welfare. Refer to at least one diagram in your answer.","marks_available":25,"question_type":"25-marker","section":"C","diagram_required":true},
    {"question_number":"4","question_text":"Evaluate the extent to which contestable markets deliver better outcomes for consumers than oligopolistic markets. Refer to at least one diagram in your answer.","marks_available":25,"question_type":"25-marker","section":"C","diagram_required":true}
  ]'::jsonb
);

-- Paper 2 June 2023
INSERT INTO public.mock_papers (exam_board, subject, paper_number, paper_name, year, total_marks, time_limit_minutes, content_source, sections, questions)
VALUES (
  'Edexcel', 'Economics', 2,
  'Edexcel Economics A Paper 2: The National and Global Economy (June 2023)',
  2023, 100, 120, 'representative',
  '[{"id":"A","name":"Section A: Data Response — UK Inflation","questions":["1a","1b","1c","1d","1e"]},{"id":"B","name":"Section B: Data Response — UK Trade","questions":["2a","2b","2c","2d","2e"]},{"id":"C","name":"Section C: Essay (choose one)","questions":["3","4"]}]'::jsonb,
  '[
    {"question_number":"1a","question_text":"With reference to Extract A, identify two significant features of the data shown.","marks_available":5,"question_type":"5-marker","section":"A","extract_text":"Extract A shows UK CPI inflation and Bank of England base rate from 2020 to 2023. CPI inflation rose from 0.7% in January 2021 to a peak of 11.1% in October 2022, before falling to 6.7% by September 2023. The Bank of England base rate was held at 0.1% until December 2021, then increased 14 consecutive times to reach 5.25% by August 2023. Average real wages fell by 3.1% in the year to March 2023."},
    {"question_number":"1b","question_text":"With reference to the information provided, explain how cost-push factors contributed to the inflationary pressures experienced by the UK economy.","marks_available":8,"question_type":"8-marker","section":"A"},
    {"question_number":"1c","question_text":"With reference to Extract B and your own knowledge, assess the effectiveness of monetary policy in controlling inflation in the UK.","marks_available":10,"question_type":"10-marker","section":"A","extract_text":"Extract B: The Bank of England''s Monetary Policy Committee raised interest rates from 0.1% to 5.25% between December 2021 and August 2023. Mortgage approvals fell by 28% in the year to July 2023. However, inflation remained above the 2% target throughout 2023. Some economists argue that monetary policy is less effective when inflation is driven by supply-side shocks rather than excess demand. Business investment fell by 1.2% in Q2 2023."},
    {"question_number":"1d","question_text":"With reference to the extracts and your own knowledge, evaluate the trade-offs the Bank of England faces when setting interest rates during a period of high inflation and low economic growth.","marks_available":12,"question_type":"12-marker","section":"A"},
    {"question_number":"1e","question_text":"Evaluate the view that fiscal policy would be more effective than monetary policy in managing the UK economy during the current macroeconomic environment.","marks_available":15,"question_type":"15-marker","section":"A"},
    {"question_number":"2a","question_text":"With reference to Extract C, identify two significant features of the data shown.","marks_available":5,"question_type":"5-marker","section":"B","extract_text":"Extract C shows the UK''s balance of trade in goods and services from 2018 to 2023. The trade deficit in goods widened from £139bn in 2018 to £186bn in 2023. The trade surplus in services grew from £108bn to £132bn over the same period. The overall current account deficit was £83bn (3.1% of GDP) in 2023. UK exports to the EU fell by 7% between 2019 and 2023, while exports to non-EU countries grew by 4%."},
    {"question_number":"2b","question_text":"With reference to the information provided, explain how a depreciating exchange rate might affect the UK''s balance of trade.","marks_available":8,"question_type":"8-marker","section":"B"},
    {"question_number":"2c","question_text":"With reference to Extract D and your own knowledge, assess the impact of increased trade barriers on the UK economy since 2021.","marks_available":10,"question_type":"10-marker","section":"B","extract_text":"Extract D: Since leaving the EU single market in January 2021, UK firms have faced new customs checks, regulatory divergence, and rules of origin requirements on exports to the EU. A 2023 study estimated that these barriers reduced UK-EU trade by approximately 15% compared to a scenario where the UK had remained in the single market. However, the UK has signed new trade agreements with Australia, New Zealand, and is seeking CPTPP membership. Small and medium-sized enterprises have been disproportionately affected, with 24% of SMEs that previously exported to the EU ceasing to do so."},
    {"question_number":"2d","question_text":"With reference to the extracts and your own knowledge, evaluate whether the UK''s comparative advantage has changed as a result of its new trading relationships.","marks_available":12,"question_type":"12-marker","section":"B"},
    {"question_number":"2e","question_text":"Evaluate the view that free trade always leads to net economic benefits for all participating countries.","marks_available":15,"question_type":"15-marker","section":"B"},
    {"question_number":"3","question_text":"Evaluate the effectiveness of supply-side policies in promoting long-run economic growth in the UK. Refer to at least one diagram in your answer.","marks_available":25,"question_type":"25-marker","section":"C","diagram_required":true},
    {"question_number":"4","question_text":"Evaluate the view that a floating exchange rate system is always preferable to a fixed exchange rate system for the UK. Refer to at least one diagram in your answer.","marks_available":25,"question_type":"25-marker","section":"C","diagram_required":true}
  ]'::jsonb
);

-- Paper 1 June 2022
INSERT INTO public.mock_papers (exam_board, subject, paper_number, paper_name, year, total_marks, time_limit_minutes, content_source, sections, questions)
VALUES (
  'Edexcel', 'Economics', 1,
  'Edexcel Economics A Paper 1: Markets and Business Behaviour (June 2022)',
  2022, 100, 120, 'representative',
  '[{"id":"A","name":"Section A: Data Response — UK Supermarkets","questions":["1a","1b","1c","1d","1e"]},{"id":"B","name":"Section B: Data Response — UK Labour Market","questions":["2a","2b","2c","2d","2e"]},{"id":"C","name":"Section C: Essay (choose one)","questions":["3","4"]}]'::jsonb,
  '[
    {"question_number":"1a","question_text":"With reference to Extract A, identify two significant features of the data shown.","marks_available":5,"question_type":"5-marker","section":"A","extract_text":"Extract A shows market share data for UK supermarkets from 2019 to 2022. Tesco''s market share fell from 27.4% to 26.9%, while Aldi''s share rose from 7.9% to 9.3% and Lidl''s from 5.9% to 7.1%. The total value of the UK grocery market grew from £203bn to £228bn over the period. Average food prices increased by 16.4% in the year to March 2023, the highest rate in 45 years."},
    {"question_number":"1b","question_text":"With reference to the information provided, explain how the characteristics of an oligopoly are demonstrated in the UK supermarket industry.","marks_available":8,"question_type":"8-marker","section":"A"},
    {"question_number":"1c","question_text":"With reference to Extract B and your own knowledge, assess the extent to which the growth of discount supermarkets has increased contestability in the UK grocery market.","marks_available":10,"question_type":"10-marker","section":"A","extract_text":"Extract B: Aldi and Lidl have opened over 400 new stores in the UK since 2015, investing £3.5bn. Their combined market share has more than doubled from 8% to 16.4% between 2015 and 2022. Aldi''s average basket price is estimated to be 20% lower than the ''Big Four'' supermarkets. However, barriers to entry remain significant — a new full-size supermarket requires investment of £30m-£50m, planning permission takes 12-18 months, and established retailers control the most desirable locations."},
    {"question_number":"1d","question_text":"With reference to the extracts and your own knowledge, evaluate the impact of non-price competition on consumer welfare in the UK supermarket industry.","marks_available":12,"question_type":"12-marker","section":"A"},
    {"question_number":"1e","question_text":"Evaluate the view that the Competition and Markets Authority (CMA) is effective in promoting competition and protecting consumers in oligopolistic markets such as the UK supermarket industry.","marks_available":15,"question_type":"15-marker","section":"A"},
    {"question_number":"2a","question_text":"With reference to Extract C, identify two significant features of the data shown.","marks_available":5,"question_type":"5-marker","section":"B","extract_text":"Extract C shows UK labour market data from 2019 to 2022. The unemployment rate fell from 3.8% in Q4 2019 to 3.5% in Q3 2022. Job vacancies reached a record 1.3 million in March 2022. Average weekly earnings growth was 6.0% in nominal terms but -2.5% in real terms in Q3 2022. The economic inactivity rate increased from 20.4% to 21.6% over the period, with over 500,000 additional people classified as long-term sick."},
    {"question_number":"2b","question_text":"With reference to the information provided, explain how the concepts of derived demand and wage determination are relevant to understanding the current UK labour market.","marks_available":8,"question_type":"8-marker","section":"B"},
    {"question_number":"2c","question_text":"With reference to Extract D and your own knowledge, assess the impact of the National Living Wage on employment and income inequality in the UK.","marks_available":10,"question_type":"10-marker","section":"B","extract_text":"Extract D: The National Living Wage increased from £8.91 to £9.50 in April 2022, with a further increase to £10.42 in April 2023. The Low Pay Commission estimated that the NLW directly increased wages for 2 million workers. Research by the London School of Economics found no significant negative impact on employment levels. However, the Federation of Small Businesses reported that 38% of small firms found the increase ''very difficult'' to absorb, with some reducing hours rather than making redundancies."},
    {"question_number":"2d","question_text":"With reference to the extracts and your own knowledge, evaluate the effectiveness of education and training policies in addressing labour market failures in the UK.","marks_available":12,"question_type":"12-marker","section":"B"},
    {"question_number":"2e","question_text":"Evaluate the view that trade unions improve economic outcomes for workers without causing significant labour market distortions.","marks_available":15,"question_type":"15-marker","section":"B"},
    {"question_number":"3","question_text":"Evaluate the view that third-degree price discrimination always benefits producers more than consumers. Refer to at least one diagram in your answer.","marks_available":25,"question_type":"25-marker","section":"C","diagram_required":true},
    {"question_number":"4","question_text":"Evaluate the view that perfect competition leads to the most efficient allocation of resources compared to other market structures. Refer to at least one diagram in your answer.","marks_available":25,"question_type":"25-marker","section":"C","diagram_required":true}
  ]'::jsonb
);

-- Paper 2 June 2022
INSERT INTO public.mock_papers (exam_board, subject, paper_number, paper_name, year, total_marks, time_limit_minutes, content_source, sections, questions)
VALUES (
  'Edexcel', 'Economics', 2,
  'Edexcel Economics A Paper 2: The National and Global Economy (June 2022)',
  2022, 100, 120, 'representative',
  '[{"id":"A","name":"Section A: Data Response — UK Government Spending","questions":["1a","1b","1c","1d","1e"]},{"id":"B","name":"Section B: Data Response — Emerging Economies","questions":["2a","2b","2c","2d","2e"]},{"id":"C","name":"Section C: Essay (choose one)","questions":["3","4"]}]'::jsonb,
  '[
    {"question_number":"1a","question_text":"With reference to Extract A, identify two significant features of the data shown.","marks_available":5,"question_type":"5-marker","section":"A","extract_text":"Extract A shows UK government spending and national debt from 2018 to 2022. Total government spending rose from £842bn (39% of GDP) in 2018/19 to £1,047bn (44% of GDP) in 2021/22, before falling to £1,029bn (43% of GDP) in 2022/23. National debt increased from £1.8 trillion (84% of GDP) to £2.5 trillion (100% of GDP) over the same period. Debt interest payments reached £111bn in 2022/23, up from £38bn in 2019/20."},
    {"question_number":"1b","question_text":"With reference to the information provided, explain the difference between a government budget deficit and the national debt, and why both are significant for macroeconomic stability.","marks_available":8,"question_type":"8-marker","section":"A"},
    {"question_number":"1c","question_text":"With reference to Extract B and your own knowledge, assess the view that austerity measures are necessary to reduce the national debt.","marks_available":10,"question_type":"10-marker","section":"A","extract_text":"Extract B: Following the COVID-19 pandemic, the UK government spent £370bn on emergency support measures. The IMF recommended that the UK pursue a ''credible medium-term fiscal consolidation'' strategy. However, the OECD noted that premature austerity following the 2008 financial crisis had slowed recovery in several European countries. The UK''s debt-to-GDP ratio at 100% compares to Japan (263%), Italy (145%), and the US (123%). Some economists argue that with historically low interest rates in recent years, governments should have borrowed more for productive investment."},
    {"question_number":"1d","question_text":"With reference to the extracts and your own knowledge, evaluate the effectiveness of automatic stabilisers versus discretionary fiscal policy in managing the economic cycle.","marks_available":12,"question_type":"12-marker","section":"A"},
    {"question_number":"1e","question_text":"Evaluate the view that the government should prioritise reducing the budget deficit over promoting economic growth.","marks_available":15,"question_type":"15-marker","section":"A"},
    {"question_number":"2a","question_text":"With reference to Extract C, identify two significant features of the data shown.","marks_available":5,"question_type":"5-marker","section":"B","extract_text":"Extract C shows economic indicators for selected emerging economies in 2022. India''s GDP growth was 6.8%, compared to 3.0% for China and 2.9% for Brazil. India''s GDP per capita (PPP) was $8,379 compared to China''s $21,476. Foreign direct investment into India reached $84bn in 2022, while FDI into China fell by 48% to $180bn. India''s services sector accounted for 53% of GDP, while manufacturing represented only 17%, compared to 28% in China."},
    {"question_number":"2b","question_text":"With reference to the information provided, explain how foreign direct investment can promote economic development in emerging economies.","marks_available":8,"question_type":"8-marker","section":"B"},
    {"question_number":"2c","question_text":"With reference to Extract D and your own knowledge, assess the extent to which globalisation has benefited developing and emerging economies.","marks_available":10,"question_type":"10-marker","section":"B","extract_text":"Extract D: Global trade as a percentage of world GDP peaked at 61% in 2008 and has since fallen to 57%. Multinational corporations account for approximately 80% of world trade. The UNCTAD World Investment Report 2022 noted that while FDI has raised productivity and employment in many developing countries, the benefits have been unevenly distributed. Countries with strong institutions and human capital — such as Vietnam, India and Bangladesh — have attracted more FDI than Sub-Saharan African nations. Critics argue that MNC profits are often repatriated rather than reinvested, and that developing countries are locked into low-value stages of global supply chains."},
    {"question_number":"2d","question_text":"With reference to the extracts and your own knowledge, evaluate the role of the World Trade Organisation in promoting economic development.","marks_available":12,"question_type":"12-marker","section":"B"},
    {"question_number":"2e","question_text":"Evaluate the view that protectionist trade policies can be justified for developing and emerging economies.","marks_available":15,"question_type":"15-marker","section":"B"},
    {"question_number":"3","question_text":"Evaluate the view that demand-side policies alone are sufficient to achieve sustained economic growth and full employment. Refer to at least one diagram in your answer.","marks_available":25,"question_type":"25-marker","section":"C","diagram_required":true},
    {"question_number":"4","question_text":"Evaluate the extent to which inequality of income and wealth is an inevitable consequence of a market economy. Refer to at least one diagram in your answer.","marks_available":25,"question_type":"25-marker","section":"C","diagram_required":true}
  ]'::jsonb
);

-- 4. Link papers to products
UPDATE public.mock_papers
SET product_id = (SELECT id FROM public.products WHERE slug = 'edexcel-economics' LIMIT 1)
WHERE exam_board = 'Edexcel' AND subject = 'Economics' AND product_id IS NULL;
